version: "3.7"

services:

    #PHP Service
    api:
        build:
            context: ./
            dockerfile: php/Dockerfile
        container_name: api
        ports:
            - "9000:9000"
        networks:
            - internal
        volumes:
            - ./php/php.ini:/etc/php/php.ini
            - ${DIR_API_ROOT}:/var/www/api
        working_dir: /var/www/api
        links:
          - "db"

    #NGINX Service
    webserver:
        build:
            context: ./
            dockerfile: nginx/Dockerfile
        container_name: webserver
        ports:
            - "80:80"
        networks:
            - internal
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/log:/var/log/nginx

    #MySQL Service
    db:
        container_name: db
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=muestra_basica
        ports:
            - "3309:3306"
        networks:
            - internal
        volumes:
            - ${DIR_DB_DATA}:/var/lib/mysql

networks:
    internal:
        driver: bridge
